language: node_js
node_js:
  - "7"

cache:
  directories:
    - "node_modules"
  yarn: true

jobs:
  include:
    - stage: test
      addons:
        chrome: stable
      env:
        - CHROME_BIN=google-chrome-stable
      script: ng test -cc -sr -sm=false --browsers=ChromeHeadlessV2
    - stage: test
      script: ng lint
    - stage: test
      script: ng build --aot
    - stage: deploy to staging
      script:
        - ng build --env=staging --aot
        - dpl --provider=firebase --token=$FIREBASE_TOKEN --project=agendaodontoweb-staging
    - stage: deploy to production
      script:
        - ng build --env=prod --aot
        - dpl --provider=firebase --token=$FIREBASE_TOKEN --project=agendaodonto-29023
