language: node_js
node_js:
  - "8"
cache:
  yarn: true
dist: trusty
stages:
  - test
  - name: deploy
    if: type = push
jobs:
  include:
    - stage: test
      addons:
        chrome: stable
      env:
        - CHROME_BIN=google-chrome-stable
      script:
        - ng test --code-coverage=true --watch=false --browsers=ChromeHeadlessNoSandBox
        - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
    - stage: test
      script: ng lint
    - stage: test
      script: ng build --aot
    - stage: deploy
      script: ./scripts/deploy.sh
