language: node_js
node_js:
  - "7"
cache:
  directories:
    - "node_modules"
  yarn: true
dist: trusty
jobs:
  include:
    - stage: test
      addons:
        chrome: stable
      env:
        - CHROME_BIN=google-chrome-stable
      script:
        - ng test -sm=false -cc -sr --browsers=ChromeHeadlessNoSandBox
        - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
    - stage: test
      script: ng lint
    - stage: test
      script: ng build --aot
    - stage: deploy
      script: ./scripts/deploy.sh
