language: node_js
node_js:
  - "7"
cache:
  directories:
    - "node_modules"
  yarn: true
dist: trusty
jobs:
  include:
    - stage: test
      addons:
        chrome: stable
      env:
        - CHROME_BIN=google-chrome-stable
      script: ng test -cc -sr
    - stage: test
      script: ng lint
    - stage: test
      script: ng build --aot
    - stage: deploy to staging
      script: ./scripts/deploy.sh
    - stage: deploy to production
      script: ./scripts/deploy.sh
