dist: trusty

language: node_js

node_js:
  - "10"

addons:
  apt:
    packages:
      - libgconf-2-4

services:
  - docker

cache:
  npm: true
  directories:
    - ~/.cache

before_install:
  # set up awscli packages
  - pip install --user awscli
  - mkdir -p ~/$TRAVIS_BUILD_NUMBER
  - aws s3 sync s3://agendaodonto-staging-builds/$TRAVIS_BUILD_NUMBER-staging/dist ./dist-staging --expires "$(date -d '+1 hour' --utc +'%Y-%m-%dT%H:%M:%SZ')"
  - aws s3 sync s3://agendaodonto-staging-builds/$TRAVIS_BUILD_NUMBER-prod/dist ./dist-prod --expires "$(date -d '+1 hour' --utc +'%Y-%m-%dT%H:%M:%SZ')"

stages:
  - name: quality
  - name: quality gate
  - name: E2E Test
  - name: deploy staging
    if: type = push AND branch = "develop" AND tag IS blank
  - name: deploy production
    if: tag IS present

jobs:
  include:
    - stage: quality
      name: Unit Tests
      if: tag IS blank
      addons:
        chrome: stable
      env:
        - CHROME_BIN=google-chrome-stable
      script:
        - ng test --code-coverage=true --watch=false --browsers=ChromeHeadless
        - aws s3 sync ./coverage s3://agendaodonto-staging-builds/$TRAVIS_BUILD_NUMBER-staging/coverage --expires "$(date -d '+1 hour' --utc +'%Y-%m-%dT%H:%M:%SZ')"

    - stage: quality
      name: Lint
      if: tag IS blank
      script: ng lint

    - stage: quality
      name: Build Staging
      if: tag IS blank
      script:
        - ng b -c=staging --aot
        - aws s3 sync ./dist s3://agendaodonto-staging-builds/$TRAVIS_BUILD_NUMBER-staging/dist --expires "$(date -d '+1 hour' --utc +'%Y-%m-%dT%H:%M:%SZ')"

    - stage: quality
      name: Build Prod
      if: tag IS present
      script:
        - ng b -c=production --prod=true --aot
        - aws s3 sync ./dist s3://agendaodonto-staging-builds/$TRAVIS_BUILD_NUMBER-prod/dist --expires "$(date -d '+1 hour' --utc +'%Y-%m-%dT%H:%M:%SZ')"
    - stage: E2E Test
      scripts: 
        - docker build -f ./dependencies/Dockerfile -t webapp .
        - docker run --rm -d -p 80:80 --name webapp webapp
        - npx cypress run
    - stage: deploy staging
      script: ./scripts/deploy.sh staging

    - stage: deploy production
      script: ./scripts/deploy.sh production

    - stage: Quality Gate
      name: Sonar
      if: tag IS blank
      script:
        - aws s3 sync s3://agendaodonto-staging-builds/$TRAVIS_BUILD_NUMBER-staging/coverage ./coverage --expires "$(date -d '+1 hour' --utc +'%Y-%m-%dT%H:%M:%SZ')"
        - sonar-scanner

addons:
  sonarcloud:
    organization: "agendaodonto"
